title: "Pietro's blog"
email: pietro@carrucciu.com
description: >- # this means to ignore newlines until "baseurl:"
  A place to share my thoughts and explore ideas.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://carruc.eu" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title

icon: /assets/images/carruc-eu-icon.png
github_username:  carruc

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-paginate

paginate: 12
paginate_path: "/page/:num/"

sass:
  style: :expanded
